### ISSUE TITLE
Compatibility with GeoInterface?

### ISSUE THREAD

**Issue by tdunning** [wookay/H3.jl#15]
What do you think it will take to get something that uses interfaces compatible with, say, LibGEOS?

See, for instance, https://github.com/JuliaGeo/GeoInterface.jl

This would help the usability of H3.jl immensely.

**Comment by wookay** [comment]
maybe work with geojson stuff.
- https://github.com/uber/geojson2h3
- https://github.com/JuliaGeo/GeoJSON.jl

**Comment by tdunning** [comment]
I was asking a bit more about your planned roadmap. Do you plan to extend the H3 package to integrate better with other geo packages in Julia.

For instance, it would be nice to be able to filter a list of hexes to select the ones that overlap a polygon defined using GeoJSON. Or to polyfill a region defined using LibGeos. Lots of geo data is out there in formats that these other packages understand.

**Comment by wookay** [comment]
oh. I don't have any plan for it. this package is just an H3 wrapper for julia.
you could create another package that using H3.

**Comment by tdunning** [comment]
That makes some sense. Here is an example of what I am working on for
making H3 easier to use. Most wrappers have something like this.

https://github.com/agstack/weather-server/blob/main/experiments/s2-geohash/geoHex.jl

If this expands, I will look into building a real package out of it.

Thanks for answering the questions!

(oh, what tooling are you using to wrap H3?)

**Comment by wookay** [comment]
follow these article and repos.
* Pkg + BinaryBuilder -- The Next Generation https://julialang.org/blog/2019/11/artifacts/
* Yggdrasil H3 https://github.com/JuliaPackaging/Yggdrasil/tree/master/H/H3
* https://github.com/wookay/H3.jl/tree/master/gen

**Comment by tdunning** [comment]
Perfect. Thanks.
