### ISSUE TITLE
Compact doesn't always return the same number of valid H3 indexes

### ISSUE THREAD

**Issue by tommwatson** [wookay/H3.jl#2]
Compact always returns an array of the same length of the input `h3Set`, however some of the returned elements are not `H3Index`es of the compacted set. Doing a list comprehension to get the valid ones yields inconsistent results.

Attached is a set of `H3Index`es and a jupyter notebook demonstrating the above.
[compact_issue.zip](https://github.com/wookay/H3.jl/files/3499324/compact_issue.zip)
And a screenshot for readability: 
![image](https://user-images.githubusercontent.com/10151166/62985559-3e7ac980-be7b-11e9-8946-43038b25546c.png).

My guess is that `undef` happens to luck onto valid `H3Index`es so my suggested fix is to initialize the `compactedSet` with zeros (an `H3Index` that is guaranteed to be invalid - see [here](https://github.com/uber/h3/blob/36a2cebd1cd292cfcfe171626df666d1885c0f18/src/h3lib/include/h3Index.h#L148)), and potentially incorporate the list comprehension to return only the valid `H3Index`es before returning. 

Happy to put up a pull request.

**Comment by wookay** [comment]
thanks for the detail report!
