### ISSUE TITLE
Package fails to build on julia-1.11

### ISSUE THREAD

**Issue by rgivry** [wookay/H3.jl#21]
First of all thanks for this amazing library. When trying to build H3 under julia-v1.11 I get the following:

# Reproduction steps
```
$ julia +1.11 --project -e "using Pkg; Pkg.update(); Pkg.test()"
ERROR: Unsatisfiable requirements detected for package BinaryProvider [b99e7846]:
 BinaryProvider [b99e7846] log:
 ├─possible versions are: 0.4.0 - 0.5.10 or uninstalled
 ├─restricted to versions 0.5 - 0.6 by H3 [f62fece2], leaving only versions: 0.5.0 - 0.5.10
 │ └─H3 [f62fece2] log:
 │   ├─possible versions are: 0.2.0 or uninstalled
 │   └─H3 [f62fece2] is fixed to version 0.2.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

Under 1.10 we don't seem to have this issue:
```
$ julia +1.10 --project -e "using Pkg; Pkg.update(); Pkg.test()"
[...]

✅  All 1140 tests have been completed.  (compile: 0.61, recompile: 0.01, elapsed: 1.30 seconds)
     Testing H3 tests passed
```

# Possible solution
I've tried removing the dependency on `BinaryBuilder` and all tests pass under `1.11.0`. Maybe releasing H3.jl `v0.2.1` with this dependency removed is the right approach?

**Comment by wookay** [comment]
hello.
could you test again with H3 v0.3.0 ?

```julia
julia> using Pkg

julia> Pkg.Registry.update()

julia> Pkg.update("H3")

julia> Pkg.test("H3")
```

**Comment by rgivry** [comment]
I've run the test on `0.3` and it's working great!

I noticed there's quite a few API changes but after porting my projects over I'm able to run my (unfortunately private) tests suites without issues.

Thanks for the quick turnaround.
